### ISSUE TITLE
Request: don't force formatting on BufWritePost

### ISSUE THREAD

**Issue by turboladen** [splattael/rufo-vim#1]
...or at any time, for that matter. I'd like to opt-in to when a call to `rufo#Format()` happens. Maybe just add to the README?

For example, I just discovered rufo and may not have it all configured how I want it (and maybe rufo doesn't support all of the options I want yet) so running it on a file that I'm editing will mess up the formatting that I want. Just having this plugin loaded locks me in to reformatting on save, which I really don't want.

**Comment by splattael** [comment]
@turboladen Good point!

Looking at @lucerion's #2 right now! This looks nice :sparkles:

**Comment by splattael** [comment]
@turboladen I've just merged #2 :+1: 

Can you try the latest `master`? :neckbeard: Thank you!

**Comment by turboladen** [comment]
Looks great! Thank you!
