### ISSUE TITLE
Rufo removes line after Rufo command run

### ISSUE THREAD

**Issue by tackeyy** [splattael/rufo-vim#10]
I love this plugin. I'm facing the below problem.

[![https://gyazo.com/b09a5c00494a0122e5f54b19b3c195d2](https://i.gyazo.com/b09a5c00494a0122e5f54b19b3c195d2.gif)](https://gyazo.com/b09a5c00494a0122e5f54b19b3c195d2)

### Operation

1. ` @test = 'test' `
2. ` :w `
3. line is gone

### vim --version

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May 28 2017 16:17:07)
MacOS X (unix) version
Included patches: 1-604
Compiled by Homebrew
```

### rufo version

```
$ bundle exec rufo -v
rufo 0.1.0
```

### .rufo

```
indent_size 2
spaces_inside_hash_brace :always
align_assignments true
align_case_when true
align_chained_calls true
```

### .vimrc

```
" Enable rufo (RUby FOrmat)
let g:rufo_auto_formatting = 1

" Enable format before saving
let g:rufo_format_before_saving = 1
```

**Comment by lucerion** [comment]
Hi @tackeyy, 

Thank you for reporting! I'm looking into.

**Comment by lucerion** [comment]
@tackeyy one question, which version of rufo gem do you use?

**Comment by tackeyy** [comment]
@lucerion Thanks for reply.

> which version of rufo gem do you use?

I use ` rufo 0.1.0 ` .

```
$ bundle exec rufo -v
rufo 0.1.0
```

**Comment by lucerion** [comment]
@tackeyy thank you!

**Comment by splattael** [comment]
@tackeyy @lucerion I can reproduce it with `let g:rufo_format_before_saving = 1`.

**Comment by lucerion** [comment]
@splattael 

One more case:

**Steps:**
* delete any line
* exit with `wq` or `x`
* open file

**Result:**
Deleted line exists

**Expected result:**
Deleted line should be removed

This issue happens because code formatting starts without last changes (before file save). `let g:rufo_format_before_saving = 1` is working ok with no modified files, but it loose last changes if file was modified.

**Comment by lucerion** [comment]
@tackeyy issue was fixed. Please, update the plugin and use only `let g:rufo_auto_formatting = 1` option (`g:rufo_format_before_saving` was removed). Feel free to reopen the issue if it reproduces.

Thank you for reporting!

**Comment by tackeyy** [comment]
@lucerion @splattael Thank you for fix. After I updated plugin and changed option, I confirmed that the problem is fixed!
