### ISSUE TITLE
Latest version just keeps the first line of a file

### ISSUE THREAD

**Issue by martinos** [splattael/rufo-vim#14]
I have updated my version of rufo-vim and when I run the "Rufo" command only the first line is kept.

I am on vim 8.0.1200 on OS X and the commit is eafcd5acaaa7cd2fa66d4f37830bb7d2b33e5c02. 

The previous commit 60241f89ba66bfaad77ec52b21dac2205eea796d is working well.

**Comment by martinos** [comment]
I tried commit 60241f89ba66bfaad77ec52b21dac2205eea796d and I got `Error: the given text is not a valid ruby program (it has syntax errors)` in my output window.

Commit 60241f89ba66bfaad77ec52b21dac2205eea796d is working well on my vim.

**Comment by lucerion** [comment]
Hi @martinos! Thank you for reporting! I'm looking into.

**Comment by lucerion** [comment]
@martinos could you, please, provide more information (rufo version, rufo config, code example)? I can't reproduce it :(

**Comment by lucerion** [comment]
@martinos could you, please, update plugin and recheck the issue?

**Comment by martinos** [comment]
Sorry, I am not having the issue anymore and I can't remember what I did. I tried to reproduce the issue by updating my rufo-vim version and I don't have the issue anymore. Maybe we can close the issue.

**Comment by lucerion** [comment]
@martinos ok, thank you!
