### ISSUE TITLE
Moving this repo to ruby-formatter/rufo-vim

### ISSUE THREAD

**Issue by splattael** [splattael/rufo-vim#8]
Hi,

I'd like to move this repo to the newly created GitHub organization @ruby-formatter.

@lucerion WDYT?

Kind regards,
  Peter

**Comment by lucerion** [comment]
@splattael I think it's good idea! :+1:

**Comment by splattael** [comment]
Done :dancing_men:

**Comment by lucerion** [comment]
:+1:
